#!/bin/bash

#-------------------------------------------------------------------------
#------------------------------INSTALAR PACOTES---------------------------

IPAC(){
INSTALAR=$(dialog --stdout --inputbox 'Digite um pacote' 0 0)
case $? in 1) GPAC ;; 255) GPAC ;; esac		

apt-get install $INSTALAR




for i in {1..100}
do
	sleep 0.032 &&
	echo $i
done | dialog --title 'Instalando... "$INSTALAR"' \ 
		--guage "$INSTALAR" 10 60			

GPAC


}

#------------------------------------------------------------------------
#---------------------------REMOVER PACOTES------------------------------

#RPAC(){
#REMOVER=$(dialog --stdout --title 'Digite o pacote a ser removido' 0 0)

#case $? in 1) GPAC ;; 255) GPAC ;; esac

#if [ $REMOVER == $INSTALAR ]; then
#	apt-get remove $REMOVER
#if [ $? != $INSTALAR ]; then
#	dialog --msgbox 'Removido!' 0 0
#fi

#elif [ $REMOVER == $INSTALAR ]; then
#	apt-get remove $REMOVE
#	dialog 'Deletado!' 0 0
#else
#	dialog 'Não encontrado' 0 0
#fi

#GPAC
#}


#------------------------------------------------------------------------
#-------------------------ATUALIZAR PACOTES------------------------------

APAC(){
ATUALIZAR=$(dialog						\
		--stdout --title 'Atualizar Pacotes'		\
		--inputbox 
		0 0)
apt-get update

GPAC
}

#----------------------------------------------------------------------
#------------------------SUB MENU PACOTES------------------------------

GPAC(){
OPCAO=$(dialog							\
		--stdout					\
		--title 'Gerenciamento de Pacotes'		\
		--menu 'Escolha uma opção: '			\
		0 0 0						\
		1 'Instalar Pacotes'				\
		2 'Remover Pacotes'				\
		3 'Atualizar Pacotes'			 	\
		4 'Exibir Pacotes'				\
		5 'Sair')

case $OPCAO in
	1) IPAC ;;
	2) RPAC ;;
	3) APAC ;;
	4) EPAC ;;
	*) MENU ;;
	
esac
}

#-------------------------------------------------------------------------------
#---------------------MENU PRINCIPAL--------------------------------------------
MENU(){
OPCAO=$(dialog						\
	--stdout --title 'MENU'				\
	--menu 'Escolha uma opção do menu: '		\
	0 0 0						\
	1 'Gerenciar Arquivos'				\
	2 'Gerenciar Usuarios'				\
	3 'Gerenciar Rede'				\
	4 'Gerenciar Dispositivos'			\
	5 'Gerenciar Repositorios'			\
	6 'Sair')

case $OPCAO in
	1) GARQ ;;
	2) GUSR ;;
	3) GRED ;;
	4) GDIS ;;
	5) GPAC ;;
	6) FIM	;;
	*) FIM  ;;
esac
}

#-------------------------------------------------------------------------------
#----------------------FIM------------------------------------------------------
FIM(){ dialog --msgbox "Até breve. volte sempre !" 0 0 
exit 0
}
#-----------------------------USUARIO E SENHA------------------------------------
USER=""
PASS=""
USUARIO=$(dialog							\
		--stdout						\
		--title 'Usuário'					\
		--inputbox 'Digite o nome do seu usuário: '		\
		0 0)
case $? in 1) FIM ;; 255) FIM ;; esac

SENHA=$(dialog								\
		--stdout						\
		--title 'Senha'						\
		--passwordbox 'Digite a sua senha:'			\
		0 0)
case $? in 1) FIM ;; 255) FIM ;; esac
[ $USUARIO == $USER ] && [ $SENHA == $PASS ] && MENU || FIM

